import "../assets/app.css";

import { Noto_Color_Emoji, Roboto_Mono } from "next/font/google";

const mono = Roboto_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  fallback: ["monospace"],
});

const noto = Noto_Color_Emoji({
  subsets: ["emoji"],
  display: "swap",
  weight: ["400"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
